services:
  gifs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    environment:
      - NODE_ENV=production
    ports:
      - "8080:80"
    restart: unless-stopped
